  /**
   * Allows for assertions on the exception thrown by this provider.
   *
   * <p>The exception thrown by a checked provider is the {@link Throwable} thrown by a call to
   * {@link CheckedProvider#get}
   *
   * @return a {@link ThrowableSubject} for asserting against the {@link Throwable} thrown by {@link
   *     CheckedProvider#get}
   */
  public ThrowableSubject thrownException() {
    T got;
    try {
      got = provider.get();
    } catch (Throwable e) {
      return check("get()'s exception").that(e);
    }
    failWithoutActual(simpleFact("expected to throw"), fact("but provided", got));
    return ignoreCheck().that(new Throwable());
  }

