  public ComputationException(Throwable cause) {
    super(cause);
  }

