  T call(InternalContext context) throws ErrorsException;

