    public SubMockFoo() throws RemoteException, BindException {
    }

