  public AsynchronousComputationException(Throwable cause) {
    super(cause);
  }

